### PR TITLE
fix: cannot create root construct in python

### LINKED ISSUE #1063: creating root construct in Python
I installed constructs version 10.1.14 via pip. I am using Python 3.9.12 and NodeJS 16.15.0. I tried to create a root construct, but it throws an exception.

```python
import constructs

constructs.Construct(None, '')
```

> jsii.errors.JavaScriptError: 
  Error: Got 'undefined' for non-optional instance of {"docs":{"summary":"The scope in which to define this construct."},"name":"scope","type":{"fqn":"constructs.Construct"}}
      at nullAndOk (/tmp/tmpnx__46nv/lib/program.js:9608:23)
      at Object.deserialize (/tmp/tmpnx__46nv/lib/program.js:9382:25)
      at Kernel._toSandbox (/tmp/tmpnx__46nv/lib/program.js:8771:69)
      at /tmp/tmpnx__46nv/lib/program.js:8819:42
      at Array.map (<anonymous>)
      at Kernel._boxUnboxParameters (/tmp/tmpnx__46nv/lib/program.js:8819:27)
      at Kernel._toSandboxValues (/tmp/tmpnx__46nv/lib/program.js:8805:29)
      at /tmp/tmpnx__46nv/lib/program.js:8420:75
      at Kernel._wrapSandboxCode (/tmp/tmpnx__46nv/lib/program.js:8848:24)
      at Kernel._create (/tmp/tmpnx__46nv/lib/program.js:8420:34)

Is this a bug? Or is there some other way I'm supposed to create a root construct in Python?

### PR DESCRIPTION
**Pull request by mrgrain**
The previous attempt in #2499 caused the static helper to be added to every construct, which was unintentional and caused side-effects. Instead export a class that does the same.

Fixes #1063

### CODE REVIEW

File: src/construct.ts [hunk 1]
```diff
@@ -561,3 +561,23 @@ Object.defineProperty(Construct.prototype, CONSTRUCT_SYM, {
   enumerable: false,
   writable: false,
 });
+
```
Comment (kaizencc) [inline src/construct.ts:564]:
```suggestion
```

**Review by kaizencc — APPROVED** [review]
