### PR TITLE
fix: constructs will not be prepared due to instanceof issue

### LINKED ISSUE #32: If multiple version of construct exists in node_modules some Constructs will not be prepared
I was developing a custom cdk constructs library (NestedStacks) and after the upgrade to a version > 1.28 stacks imported from my library are not prepared. The issue was due to the fact that I was using 
`npm link` to test locally the library, in this case a copy of the dependencies exists in the node_module under the linked path.

I found the source of the problem in the implementation of the prepare() method on Construct in this library. `instanceof` breaks in this case so it would be better to use a type guard function (in the previous versions of cdk.Construct was handled in this way)

Using npm pack and then install the tar.gz file is a good temporary workaround.

### PR DESCRIPTION
**Pull request by apalumbo**
## Commit Message

Use duck-typing so that `prepare` will recognize constructs without using `instanceof`m, which breaks if prototype does not match.

Fixes #32 

## End of Commit Message

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: lib/construct.ts [hunk 1]
```diff
@@ -435,8 +436,8 @@ export class Node {
 
     // since constructs can be added to the tree during invokeAspects, call findAll() to recreate the list.
     // use PREORDER.reverse() for backward compatability
-    for (const construct of this.findAll(ConstructOrder.PREORDER).reverse()) {
-      if (construct instanceof Construct) {
+    for (const construct of this.findAll(ConstructOrder.PREORDER).reverse()) {      
+      if (Construct.isConstruct(construct)) {
```
Comment (eladb) [inline lib/construct.ts:440]: I am not sure this change makes sense. Technically `this.findAll` returns an array of `Construct` objects.

Since this is dynamic anyway, I wonder if actually the correct fix here should be:

```ts
const cn = construct as any;
if ('onPrepare' in cn) {
  if (typeof(cn.onPrepare) !== 'function') { throw new Error(`expecting "onPrepare" to be a function`); }
  cn.onPrepare();
}
```

Comment (apalumbo) [reply lib/construct.ts:440]: I tried to be conservative after checking the old code in cdk, lgtm i will change it

Comment (apalumbo) [reply lib/construct.ts:440]: I didn't have enough time to think about writing a test that mutates the prototipe of a construct just to raise the issue, I will appreciate some help.
Of course I will write the tests to ensure that all the onPrepare functions will be run, and the others use cases

Comment (apalumbo) [reply lib/construct.ts]: test added
