### PR TITLE
fix: rootNode.getAllContext() returns empty object 

### LINKED ISSUE #2239: app.getAllContext() returns empty object
I am attempting to parse some context values from the CDK app. The feature was introduced by https://github.com/aws/constructs/pull/1751

My code snippet is:

```
const app = new cdk.App();
console.log(app.node.getAllContext());
```

Which outputs:
```
{}
```

However, when I toss a `console.log()` in `Node.getAllContext()`, it prints my context variables:

```
console.log(this._context)
```

Outputs:
```
...
  '@aws-cdk/aws-ec2:restrictDefaultSecurityGroup': true,
  '@aws-cdk/aws-apigateway:requestValidatorUniqueId': true,
  longTermStorageBucketArn: 'backups-690e',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
...
```

Where `longTermStorageBucketArn` is the context I have passed on command line:

```
npm run cdk -- -c longTermStorageBucketArn=backups-690e synth
```

---

I also tested it in the constructor of a `Stack` object:

```
console.log('all context', this.node.getAllContext())
// as well as
console.log('all context', scope.node.getAllContext())
```

both of which produce:

```
all context {}
```

---

Is this the intended behavior? I don't seem to understand how to get all context from the `app` object, whereas `app.node.getContext(...)` works as expected.

### PR DESCRIPTION
**Pull request by nvinson**
Correct getAllContext() to return the root node's context in addition to specified defaults.

Fixes: #2239

### CODE REVIEW

File: src/construct.ts [hunk 1]
```diff
@@ -245,14 +245,8 @@ export class Node {
...
-    if (typeof defaults === 'undefined') {
-      defaults = {};
-    }
-
-    if (this.scope === undefined) { return defaults; }
-
-    const value = { ...this._context, ...defaults };
-    return this.scope && this.scope.node.getAllContext(value);
+    return this.scopes.reverse()
+        .reduce((a, s) => ({ ...(s.node._context), ...a }), { ...defaults });
```
Comment (mrgrain) [inline src/construct.ts]:
```suggestion
      .reduce((a, s) => ({ ...(s.node._context), ...a }), { ...defaults });
```

File: test/construct.test.ts [hunk 2]
```diff
@@ -150,6 +150,23 @@ test('construct.getContext(key) throws if context is not defined', () => {
...
+  // GIVEN
+  const context = {
+    ctx1: 12,
+    ctx2: 'hello',
+  };
+
+  // WHEN
+  const t = new Root();
+  for (const [k, v] of Object.entries(context)) {
+      t.node.setContext(k, v);
```
Comment (mrgrain) [inline test/construct.test.ts]:
```suggestion
    t.node.setContext(k, v);
```

**Review by mrgrain — APPROVED** [review]
Thanks for the fix!
